server:
  port: 80
spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/tree?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
  jpa:
      database: mysql
      show-sql: false
      hibernate:
        ddl-auto: update
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
      cache: false